"""Roboflow workflow plugin blocks backed by Livepeer services."""

from .config import (
    AUDIO_DIARIZED_TRANSCRIPTION_RUNNER_URL_ENV,
    DEFAULT_AUDIO_DIARIZED_TRANSCRIPTION_RUNNER_URL,
    DEFAULT_FLORENCE2_RUNNER_URL,
    DEFAULT_LOCAL_AUDIO_INGEST_URL,
    DEFAULT_NEMO_DIARIZED_RUNNER_URL,
    DEFAULT_OPEN_CLEARINGHOUSE_URL,
    DEFAULT_ROBOFLOW_INFERENCE_URL,
    DEFAULT_VISION_CAPABILITY,
    DEFAULT_TRUE_STREAMING_CAPABILITY,
    DEFAULT_TRUE_STREAMING_OFFERING,
    DEFAULT_TRUE_STREAMING_TRANSCRIPTION_BACKEND,
    DEFAULT_VDO_SIGNALING_SERVER_URL,
    DEFAULT_VISION_BACKEND,
    DEFAULT_VISION_OFFERING,
    FLORENCE2_RUNNER_URL_ENV,
    LOCAL_AUDIO_INGEST_URL_ENV,
    ROBOFLOW_API_KEY_ENV,
    ROBOFLOW_INFERENCE_URL_ENV,
    TRUE_STREAMING_CAPABILITY_ENV,
    TRUE_STREAMING_OFFERING_ENV,
    TRUE_STREAMING_TRANSCRIPTION_BACKEND_ENV,
    VDO_SIGNALING_SERVER_URL_ENV,
    VISION_BACKEND_ENV,
    VISION_CAPABILITY_ENV,
    VISION_OFFERING_ENV,
    init_florence2_runner_url,
    init_local_audio_ingest_url,
    init_nemo_diarized_runner_url,
    init_open_clearinghouse_api_key,
    init_open_clearinghouse_url,
    init_roboflow_api_key,
    init_roboflow_inference_url,
    init_true_streaming_capability,
    init_true_streaming_offering,
    init_true_streaming_transcription_backend,
    init_vision_backend,
    init_vision_capability,
    init_vision_offering,
    init_vdo_signaling_server_url,
)

REGISTERED_INITIALIZERS = {
    "api_key": init_open_clearinghouse_api_key,
    "base_url": init_open_clearinghouse_url,
    "runner_url": init_nemo_diarized_runner_url,
    "local_audio_ingest_url": init_local_audio_ingest_url,
    "vdo_signaling_server_url": init_vdo_signaling_server_url,
    "roboflow_api_key": init_roboflow_api_key,
    "roboflow_inference_url": init_roboflow_inference_url,
    "vision_backend": init_vision_backend,
    "florence2_runner_url": init_florence2_runner_url,
    "livepeer_api_key": init_open_clearinghouse_api_key,
    "livepeer_base_url": init_open_clearinghouse_url,
    "vision_capability": init_vision_capability,
    "vision_offering": init_vision_offering,
    "transcription_backend": init_true_streaming_transcription_backend,
    "livepeer_capability": init_true_streaming_capability,
    "livepeer_offering": init_true_streaming_offering,
}


def load_blocks():
    """Entry point used by Roboflow Inference WORKFLOWS_PLUGINS."""
    from .block import (
        LivepeerAudioDiarizedTranscribeLocalV1,
        LivepeerAudioTranscribeV1,
        LivepeerFlorence2ScreenSlideAnalysisV1,
        LivepeerLocalAudioIngressLiveAudioSourceV1,
        LivepeerLocalAudioIngressTrueStreamingTranscriptionSessionV1,
        LivepeerPCM16AudioTransformV1,
        LivepeerScreenSlideCaptureV1,
        LivepeerTranscriptOutputV1,
        LivepeerTrueStreamingTranscriptionSessionV1,
        LivepeerVDONinjaDirectTrueStreamingSessionV1,
        LivepeerVDONinjaLiveDiarizedSessionV1,
        LivepeerVDONinjaLiveAudioSourceV1,
        LivepeerVDONinjaMediaSourceV1,
        LivepeerVDONinjaRollingAudioCaptureV1,
        LivepeerVDONinjaTrueStreamingSessionV1,
    )

    return [
        LivepeerAudioTranscribeV1,
        LivepeerVDONinjaRollingAudioCaptureV1,
        LivepeerAudioDiarizedTranscribeLocalV1,
        LivepeerVDONinjaLiveDiarizedSessionV1,
        LivepeerVDONinjaTrueStreamingSessionV1,
        LivepeerVDONinjaMediaSourceV1,
        LivepeerVDONinjaLiveAudioSourceV1,
        LivepeerLocalAudioIngressLiveAudioSourceV1,
        LivepeerPCM16AudioTransformV1,
        LivepeerTrueStreamingTranscriptionSessionV1,
        LivepeerLocalAudioIngressTrueStreamingTranscriptionSessionV1,
        LivepeerTranscriptOutputV1,
        LivepeerScreenSlideCaptureV1,
        LivepeerFlorence2ScreenSlideAnalysisV1,
        LivepeerVDONinjaDirectTrueStreamingSessionV1,
    ]


__all__ = [
    "DEFAULT_OPEN_CLEARINGHOUSE_URL",
    "DEFAULT_AUDIO_DIARIZED_TRANSCRIPTION_RUNNER_URL",
    "DEFAULT_FLORENCE2_RUNNER_URL",
    "DEFAULT_NEMO_DIARIZED_RUNNER_URL",
    "DEFAULT_ROBOFLOW_INFERENCE_URL",
    "DEFAULT_VISION_CAPABILITY",
    "DEFAULT_TRUE_STREAMING_TRANSCRIPTION_BACKEND",
    "DEFAULT_TRUE_STREAMING_CAPABILITY",
    "DEFAULT_TRUE_STREAMING_OFFERING",
    "DEFAULT_VISION_BACKEND",
    "DEFAULT_VISION_OFFERING",
    "AUDIO_DIARIZED_TRANSCRIPTION_RUNNER_URL_ENV",
    "FLORENCE2_RUNNER_URL_ENV",
    "LOCAL_AUDIO_INGEST_URL_ENV",
    "ROBOFLOW_API_KEY_ENV",
    "ROBOFLOW_INFERENCE_URL_ENV",
    "TRUE_STREAMING_TRANSCRIPTION_BACKEND_ENV",
    "TRUE_STREAMING_CAPABILITY_ENV",
    "TRUE_STREAMING_OFFERING_ENV",
    "VISION_BACKEND_ENV",
    "VISION_CAPABILITY_ENV",
    "VISION_OFFERING_ENV",
    "VDO_SIGNALING_SERVER_URL_ENV",
    "REGISTERED_INITIALIZERS",
    "DEFAULT_LOCAL_AUDIO_INGEST_URL",
    "DEFAULT_VDO_SIGNALING_SERVER_URL",
    "init_florence2_runner_url",
    "init_local_audio_ingest_url",
    "init_nemo_diarized_runner_url",
    "init_open_clearinghouse_api_key",
    "init_open_clearinghouse_url",
    "init_roboflow_api_key",
    "init_roboflow_inference_url",
    "init_true_streaming_capability",
    "init_true_streaming_offering",
    "init_true_streaming_transcription_backend",
    "init_vision_backend",
    "init_vision_capability",
    "init_vision_offering",
    "init_vdo_signaling_server_url",
    "load_blocks",
]
